server:
  port: 11000
  servlet:
    context-path: /ids
logging:
  config: classpath:logback-spring.xml
  path: /var/log/${spring.application.name}
  level:
    root: ERROR
    com.xtt: DEBUG
    org.springframework: ERROR
    org.springframework.boot.autoconfigure: INFO

spring:
  profiles:
    active: dev
  application:
    name: sky-ids

